name: CI_MAIN
on:
    push:
        branches: [master]
    workflow_dispatch:
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

#debian runner
jobs:
    update:
        timeout-minutes: 2880
        runs-on: web1

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20.x"
            - name: Install dependencies
              run: npm install
            - name: Run script file
              run: |
                  chmod +x "${GITHUB_WORKSPACE}/.github/scripts/update.main.sh"
                  "${GITHUB_WORKSPACE}/.github/scripts/update.main.sh"
              shell: bash
